apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      purpose: frontend
  template:
    metadata:
      labels:
        app: wordpress
        purpose: frontend
    spec:
      containers:
      - image: wordpress
        name: wordpress-deploy
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbpassword
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: volume-mount
          mountPath: /var/www/html
      volumes:
      - name: volume-mount
        persistentVolumeClaim:
          claimName: wordpress-pvc
